### PR TITLE
Fix/updates to deprecation

### PR DESCRIPTION
**Pull request by dowatugkins**
I found a better example of how someone fixed their deprecation issues here.

I played with the example you showed not working and it looks like its working to me, but you know more about how this package works so I would recommend thorough testing before merging. 

Let me know if you find any other cases it doesn't work, but I think I just missed this one part.

### CODE REVIEW

**Comment by sompylasar** [comment]
@dowatugkins Thanks! I'd rather you test it please, and record some videos of working behavior. The behavior is conceptually simple: when moving around empty lines, the cursor has to remain at the level of indentation corresponding to this line, and the undo after such movements has to be one-step; it should also remove trailing whitespace where it added them on the empty lines to offset the cursor.

### Example

`|` stands for the cursor, `·` stands for a space character.

Create new file, set language to JavaScript:
```js
|
```

Type `function () {}`:
```js
function () {}|
```

Move cursor into `{|}`:
```js
function () {|}
```

Press Enter (built-in auto-indent works):
```js
function () {
··|
}
```

Press Enter (atom-cursor-indent works):
```js
function () {

··|
}
```

Type `if (1) {}`:
```js
function () {

··if (1) {}|
}
```

Move cursor into `{|}`:
```js
function () {

··if (1) {|}
}
```

Press Enter (built-in auto-indent works):
```js
function () {

··if (1) {
····|
··}
}
```

Press Enter (atom-cursor-indent works):
```js
function () {

··if (1) {

····|
··}
}
```

Press Enter (atom-cursor-indent works):
```js
function () {

··if (1) {


····|
··}
}
```

Move up one line (atom-cursor-indent works):
```js
function () {

··if (1) {

····|

··}
}
```

Move up one line (atom-cursor-indent works):
```js
function () {

··if (1) {
····|


··}
}
```

Move down one line (atom-cursor-indent works):
```js
function () {

··if (1) {

····|

··}
}
```

Move down one line (atom-cursor-indent works):
```js
function () {

··if (1) {


····|
··}
}
```

Move down one line (cursor stays at the end of the line, out of `}`):
```js
function () {

  if (1) {



··}|
}
```

Press Enter (atom-cursor-indent works):
```js
function () {

··if (1) {



··}
··|
}
```

**Comment by dowatugkins** [comment]
out

**Comment by sompylasar** [comment]
@dowatugkins OK, what about undo? And it would be nice if it was slower so that all the intermediate states are clearly visible. Thanks!

**Comment by dowatugkins** [comment]
Yeah, I didn't realize it was going to speed it up when I converted it to a gif. Undo seems to work properly( I'm assuming you meant ctrl-z)
out

Interestingly I noticed a couple of the flickers you can see here when moving up and down while I was writing this out, but the video caught it pretty much on every line.

**Comment by sompylasar** [comment]
> Yeah, I didn't realize it was going to speed it up when I converted it to a gif. Undo seems to work properly( I'm assuming you meant ctrl-z)

Thanks, I see now. I still don't see undo behavior on the recording though (yes, ctrl-z). What do you exactly mean by "properly"?

> Interestingly I noticed a couple of the flickers you can see here when moving up and down while I was writing this out, but the video caught it pretty much on every line.

Yes, unfortunately, that's how it's implemented. Firstly, there's no virtual whitespace in Atom, so there has to be whitespace in the buffer to be able to put a cursor there. Secondly, the plugin handles the cursor movement after it happens, not before, so if there is no whitespace on the line where the cursor moves, it moves to the beginning, then the indent logic kicks in and adds the whitespace characters.

**Comment by dowatugkins** [comment]
I mean that it did what I expected it to do, removing both the new line and the indentation associated with it. I didn't test the Undo during the video so it isn't there, but when I saw your comment later I went back and tested in in my own project.

**Comment by sompylasar** [comment]
Okay, let's release this then.

**Comment by sompylasar** [comment]
Published as `v0.3.3`: https://github.com/sompylasar/atom-cursor-indent/releases/tag/v0.3.3

**Pull request merged**
